// Complex word → simple word lookup table.
// Only base forms needed — wordSimplifier.ts handles -s / -ed / -ing variants.
// Add irregular forms (e.g. "obtained": "got") as separate entries.
export const simpleWords: Record<string, string> = {
  // common formal verbs
  utilize: 'use',
  commence: 'start',
  terminate: 'end',
  facilitate: 'help',
  endeavor: 'try',
  ascertain: 'find',
  procure: 'get',
  obtain: 'get',
  comprehend: 'understand',
  demonstrate: 'show',
  inquire: 'ask',
  purchase: 'buy',
  inform: 'tell',
  reside: 'live',
  encounter: 'meet',
  acquire: 'get',
  attempt: 'try',
  accomplish: 'do',
  achieve: 'reach',
  anticipate: 'expect',
  approve: 'okay',
  assist: 'help',
  attribute: 'credit',
  augment: 'add',
  cease: 'stop',
  clarify: 'explain',
  collaborate: 'work with',
  combine: 'mix',
  compensate: 'pay',
  complete: 'finish',
  comprise: 'include',
  conceal: 'hide',
  conduct: 'do',
  configure: 'set up',
  connect: 'link',
  consider: 'think about',
  construct: 'build',
  contemplate: 'think',
  contribute: 'give',
  convey: 'tell',
  decline: 'drop',
  decrease: 'lower',
  depart: 'leave',
  determine: 'decide',
  diminish: 'reduce',
  discontinue: 'stop',
  discover: 'find',
  disseminate: 'spread',
  duplicate: 'copy',
  elevate: 'raise',
  eliminate: 'remove',
  emphasize: 'stress',
  employ: 'use',
  enhance: 'improve',
  ensure: 'make sure',
  enumerate: 'list',
  establish: 'set up',
  estimate: 'guess',
  evaluate: 'judge',
  exceed: 'pass',
  exhibit: 'show',
  expedite: 'speed up',
  fabricate: 'make up',
  fluctuate: 'change',
  formulate: 'plan',
  generate: 'make',
  identify: 'name',
  implement: 'do',
  indicate: 'show',
  initiate: 'start',
  investigate: 'look into',
  locate: 'find',
  maintain: 'keep',
  manufacture: 'make',
  modify: 'change',
  monitor: 'watch',
  notify: 'tell',
  observe: 'watch',
  operate: 'run',
  participate: 'join',
  perceive: 'see',
  permit: 'allow',
  possess: 'own',
  preserve: 'keep',
  prevent: 'stop',
  prohibit: 'ban',
  pursue: 'chase',
  quantify: 'count',
  recommend: 'suggest',
  relinquish: 'give up',
  represent: 'show',
  require: 'need',
  respond: 'answer',
  retain: 'keep',
  revise: 'change',
  summarize: 'sum up',
  supervise: 'oversee',
  surrender: 'give up',
  transmit: 'send',
  transpire: 'happen',
  undertake: 'do',
  verify: 'check',
  visualize: 'picture',
  witness: 'see',

  // formal adjectives
  abundant: 'plenty',
  adequate: 'enough',
  additional: 'extra',
  apparent: 'clear',
  beneficial: 'helpful',
  brilliant: 'bright',
  capable: 'able',
  crucial: 'key',
  definitive: 'final',
  detrimental: 'harmful',
  equivalent: 'equal',
  explicit: 'clear',
  fundamental: 'basic',
  numerous: 'many',
  optimum: 'best',
  permanent: 'lasting',
  preliminary: 'early',
  significant: 'big',
  sufficient: 'enough',
  supplementary: 'extra',
  uniform: 'same',

  // formal adverbs / connectives
  approximately: 'about',
  consequently: 'so',
  currently: 'now',
  eventually: 'later',
  furthermore: 'also',
  immediately: 'now',
  nonetheless: 'still',
  nevertheless: 'still',
  presently: 'now',
  primarily: 'mainly',
  subsequently: 'then',
  ultimately: 'finally',

  // formal nouns
  assistance: 'help',
  alteration: 'change',
  component: 'part',
  individual: 'person',
  initiation: 'start',
  inception: 'start',
  magnitude: 'size',
  modification: 'change',
  obligation: 'duty',
  objective: 'goal',
  perspective: 'view',
  portion: 'part',
  remainder: 'rest',
  residence: 'home',
  vehicle: 'car',
}
